### ISSUE TITLE
Flesh out Meta-analysis section

### ISSUE THREAD

**Issue by garretchristensen** [garretchristensen/BestPracticesManual#16]
What are a couple of the most famous meta-analyses in psychology? I added a short section on meta-analysis, but I only know refs from medicine and econ.

**Comment by EvanMisshula** [comment]
You may want to take a look at the campbell collaboration.  They conduct systematic reviews of varying quality on CJ studies (http://www.campbellcollaboration.org)

**Comment by garretchristensen** [comment]
Added psych (big 5 and implicit association) as well as Cochrane, Campbell, and US gov't: CLEAR and WWC.
